modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "powerfuljs"
version = "${version}"
displayName = "PowerfulJS"
authors = "Prunoideae"
description = '''
Extending the KubeJS
'''
logoFile = ""

[[dependencies.powerfuljs]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.powerfuljs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.powerfuljs]]
modId = "architectury"
mandatory = true
versionRange = "[4.1.39,)"
ordering = "AFTER"
side = "BOTH"